services:
  weatherapi:
    image: ${DOCKER_REGISTRY-}weatherapi
    build:
      context: .
      dockerfile: WeatherApi/Dockerfile
  redis :
    image: redis
    ports:
     - 6379:6379
    volumes:
     - redis_data:/data
volumes:
       redis_data: 
         driver: local